name: distribution_calculator
description: Distribution Calculator

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  catex: ^0.0.1+6
  syncfusion_flutter_charts: ^18.3.47
  decimal: ^0.3.5
  expressions: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
